version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:8.10'
    steps:
      - checkout
      - run:
          name: Download dependencies
          command: yarn
      - run:
          name: Build
          command: yarn tsc
      - run:
          name: Test
          command: echo done!
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths: ~/project


  release:
    docker:
      - image: 'circleci/node:8.10'
    steps:
      - restore_cache:
          name: Restore workspace cache
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Release
          command: yarn release --dry-run

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - master 

