version: 2
jobs:
  build_and_test:
    docker:
      - image: 'circleci/node:8.10'
    steps:
      - checkout
      - run:
          name: Download dependencies
          command: yarn
      - run:
          name: Test
          command: echo done!

 release:
   steps:
     - run:
         name: Release
         command: yarn release

workflows:
  version: 2
  build_and_release:
    jobs:
      - build_and_test:
          context: org-global
      - release:
          context: org-global
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master 

