version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:8.10'
    steps:
      - checkout
      - run:
          name: Download dependencies
          command: yarn
      - run:
          name: Test
          command: echo done!

  release:
    steps:
      - run:
          name: Release
          command: yarn release

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
        requires:
        - build
        filters:
          branches:
            only:
            - master 
