version: 2
workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          context: org-global
      - release:
          context: org-global
          requires:
            - build
          filters:
            branches:
              only:
                - master 

jobs:
  build:
    docker:
      - image: 'circleci/node:8.10'
    steps:
      - checkout
      - run:
          name: Download dependencies
          command: yarn
      - run:
          name: Test
          command: echo done!

   release:
     steps:
       - run:
           name: Release
           command: yarn release

