version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:8.10'
    steps:
      - checkout
      - run:
          name: Download dependencies
          command: yarn
#      - run:
#          name: Release
#          command: yarn release
